### PR TITLE
Remove obsolete "application" DisplayCaptureSurfaceType

### PR DESCRIPTION
**Pull request by beaufortfrancois**
PTAL

***
<a href="https://pr-preview.s3.amazonaws.com/beaufortfrancois/mediacapture-screen-share/pull/243.html" title="Last updated on Oct 13, 2022, 2:37 PM UTC (f826247)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-screen-share/243/15bf8bd...beaufortfrancois:f826247.html" title="Last updated on Oct 13, 2022, 2:37 PM UTC (f826247)">Diff</a>

### CODE REVIEW

**Review by eladalon1983 — APPROVED** [review]

**Comment by alvestrand** [comment]
please grep for "application" before merging.

**Comment by eladalon1983** [comment]
I've pushed some additional changes into your PR, @beaufortfrancois. It was hard to suggest changes because of the size of the file and how the changes were in far flung areas of the document. Does that look fine to you? If so, I will merge.

**Comment by beaufortfrancois** [comment]
LGTM. Thanks!

**Comment by eladalon1983** [comment]
Thank you.

**Pull request merged**
