### PR TITLE
Add user activation check when calling getDisplayMedia

### PR DESCRIPTION
**Pull request by youennf**

### CODE REVIEW

**Comment by youennf** [comment]
PR for https://github.com/w3c/mediacapture-screen-share/issues/104

**Comment by martinthomson** [comment]
This is fine, though I wonder if this is not something that needs to be fixed more generically in the permissions API.

**Comment by youennf** [comment]
I am not sure we can always integrate this user gesture with something like "prompt the user to choose".
It might be best from a web developer perspective that an API always/never requires a user gesture.
Also, if we had that user gesture check in place for getUserMedia, doing the check as the first step of the algorithm would decrease the possibility to use getUserMedia as a probing/fingerprinting vector.

Or are you suggesting a new "retrieve callable state" hook defined in the Permissions API?

I am fine having that discussion in Permissions API.
I would prefer moving forward with this PR in parallel.

**Comment by martinthomson** [comment]
I agree.  This can progress here and then we can move to depend on whatever changes happen in permissions.

Folks at Mozilla would prefer to provide more information about permissions, such as any requirement for user activation.

**Review by jan-ivar — APPROVED** [review]

**Comment by alvestrand** [comment]
Any comments on whether "InvalidStateError" is the right code to use?

**Pull request merged**
