### PR TITLE
Add conversational sharing use case, non-goals and alternatives

### PR DESCRIPTION
**Pull request by jan-ivar**
Forgot this use-case in https://github.com/w3c/mediacapture-screen-share/pull/122.

### CODE REVIEW

**Comment by aboba** [comment]
@jan-ivar Typically the tech support use case also involves "take control" which is out of scope.

**Comment by jan-ivar** [comment]
@aboba I didn't mean to imply that was in scope. Is there a better phrasing that avoids it?

**Comment by jan-ivar** [comment]
I'm trying to capture a non-conference non-presentation use case.

I Skype with my dad a lot, and for us to be able to spontaneously share things we're looking at on our computers and on the web, is useful and complementary to our conversation. I don't have to pause and worry whether he's seeing the exact same thing as me or not.

If he has a question about how to do something on his computer, he is able to share his screen so I can see what he sees and guide him. It's outside his skill set to install and establish VNC.

**Comment by jan-ivar** [comment]
These use cases do not seem satisfied by an online document sharing solutions.

**Comment by aboba** [comment]
@jan-ivar Having been in the "parental computer support" situation myself, there is a point at which  "show me your screen and I'll help you figure things out" can transition to "give me control and let me show you how to do it".   The explainer just needs to be clear that we can't cross that line.

**Review by aboba — APPROVED** [review]

**Review by henbos — APPROVED** [review]

**Pull request merged**
