### PR TITLE
Reflow with tidy

### PR DESCRIPTION
**Pull request by dontcallmedom**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-screen-share/pull/279.html" title="Last updated on Oct 26, 2023, 5:09 PM UTC (d8cd0ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-screen-share/279/881fd35...d8cd0ad.html" title="Last updated on Oct 26, 2023, 5:09 PM UTC (d8cd0ad)">Diff</a>

### CODE REVIEW

**Comment by henbos** [comment]
Needs rebase

**Comment by jan-ivar** [comment]
@dontcallmedom this is a big PR, can you resolve the merge conflicts for us?

**Comment by dontcallmedom** [comment]
see https://github.com/w3c/mediacapture-screen-share/pull/273#issuecomment-1710270152 - should I instead reflow-and-merge without waiting for reviews?

**Comment by jan-ivar** [comment]
@dontcallmedom please do!

**Comment by aboba** [comment]
@dontcallmedom Yes, go ahead.

**Pull request merged**
